### ISSUE TITLE
renconstruct custom task wrong methods invoked

### ISSUE THREAD

**Issue by dismalarts** [kobaltcore/renkit#11]
It appears that (for a pre-build task), a method called `preBuild` is invoked, instead of `pre_build`.

`Creating Renpy builds
Using Ren'Py version 8.1.1
Python Support: true
Python Version: 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
Scanning tasks in directory 'tasks'...
Loaded Task: SetVersionTask
Loaded Task: clean
Loaded 2 tasks
Running pre-build task set_version with priority 0
nimpy.nim(842)           callMethodAux
Error: unhandled exception: No callable attribute: preBuild [ValueError]`

**Comment by kobaltcore** [comment]
Thanks for the report, I'll look into this soon and get back to you.

**Comment by kobaltcore** [comment]
Thanks for the report, I found and resolved the issue. Will push a new release momentarily.
