### ISSUE TITLE
Packing DMGs without hdiutil / Alternative archive compression option

### ISSUE THREAD

**Issue by furudean** [kobaltcore/renkit#16]
the use of `hdiutil` to pack dmg files essentially enforces use of macos environment to do notarization, as it's proprietary apple software. this is tricky in CI environments, as macos runners are expensive and hard to come by. it would be great if there was

1. an option to skip notarization of the disk image
2. using an alternative to `hdiutil` to create the disk image
3. an option to compress the app file using a more portable format, like zip, and notarize that archive instead

any of these would solve my problem, but 2 and 3 are the most attractive

**Comment by kobaltcore** [comment]
Yeah, I've been looking into ways to handle this somewhat gracefully as well. There is some work ongoing in a Rust library that is able to read disk images, but so far does not feature write support. I was kinda hoping it'd be supported by now, but given that this format is likely arcane and somewhat cursed, I understand why it's still a ways off.

In absence of the 'correct' way of supporting disk images, I'm also leaning towards what you mention in option 3, that being falling back to ZIP notarization on platforms that don't support disk images. I will try and implement support for this for the next release, but given that this is a somewhat more complicated feature, it might take a couple of weeks to land.

There is a lot of work to be done in regards to proper iOS build support as well, which I'll tackle eventually.

**Comment by furudean** [comment]
Cursed is the word. It's insane that `hdiutil` isn't provided to any other platform. Perhaps an intentionally hostile choice by Apple to lock it down 🤷‍♀️

As always, I'm grateful for your time looking into this!

**Comment by kobaltcore** [comment]
I've released `4.1.0` which introduces a slightly revamped notarization process which hopefully is more useful on non-Apple platforms. Once the release is done, give it a try if you want and let me know whether this helps.

**Comment by kobaltcore** [comment]
Closing since this is presumably fixed. Please reopen in case it's not.

**Comment by furudean** [comment]
It works great, thank you! This will definitely do for me
