### ISSUE TITLE
Set custom key alias and password

### ISSUE THREAD

**Issue by fleetingheart** [kobaltcore/renkit#18]
Hi, would it be possible to add ability for specifying your own password and alias for keystore file?
In RenPy, we have to edit the `local.properties` file in the `rapt/project` directory.
It would be cool to have a more straightforward way to handle this.
-Ikariya

**Comment by kobaltcore** [comment]
Absolutely, that should be possible and is a nice feature request! I'll add it to my todo list for the next release, will notify here once it's up :)

**Comment by kobaltcore** [comment]
The just-released `v4.3.0` should now support `alias` and `password` settings in the config file, please give it a try and let me know how it works out for you!

**Comment by fleetingheart** [comment]
Hi, just checked build in GH Actions. Works great, thx for such useful tool :)
-Ikariya
