### ISSUE TITLE
README error?

### ISSUE THREAD

**Issue by Rucadi** [kobaltcore/renkit#19]
In the readme there is a table where it marks that Linux aarch64 is not available, however, in the releases there is an aarch64 linux version, is this an error in the readme? Or it means the target?

**Comment by kobaltcore** [comment]
The table is correct. While `renkit` itself already supports `aarch64`, Ren'Py doesn't. So you can actually install `renkit` on ARM-based Linux systems and it'll mostly run, but will be incapable of installing any version of Ren'Py as they don't ship with the required libraries.
You can verify this yourself by downloading i.e. the latest version at the moment (`8.3.0`) and checking the `lib` folder, which you'll find lacking libraries for `aarch64`.

There are ARM versions available as standalone downloads, though those are specifically targeted at Raspberry Pi's and Chromebooks. I might integrate those into `renkit` eventually, but would rather prefer proper support for generic ARM Linux in Ren'Py proper instead. I'll send renpytom a message to see what the status of that is, but no promises at the moment.

In the meantime, I've clarified the support table in the README a bit, hopefully it's easier to parse now.
