### ISSUE TITLE
`renutil launch` sourcing renpy version to use from file

### ISSUE THREAD

**Issue by furudean** [kobaltcore/renkit#26]
it would be nice if the right version of renpy to use could be declared in a checked out file like renconstruct.toml. this is already used for builds, so i think wanting to launch the game with that same version while working on it makes sense. idk, thoughts? it might not semantically make sense to pull a renutil version from a reconstruct config

**Comment by kobaltcore** [comment]
Do you mean something like what Python/pyenv has with a `.python-version` file per project? It could be read from the project path (which is supplied anyway) and `renutil` could then select (and optionally auto-install) the required version. In that case it could be a `.renpy-version` file.
There is also sometimes a `script_version.txt` file that Ren'Py creates (at least in built distributions) so maybe using that one could also work, but it has the chance to conflict with whatever Ren'Py proper does with it.

**Comment by furudean** [comment]
I'm fine with any of these

**Comment by kobaltcore** [comment]
Got a prototype of this working in a feature branch, its functionality is explained in the changelog in the commit referenced above. This will eventually make it into a pre-release for public testing.
