### ISSUE TITLE
Missing SSL support

### ISSUE THREAD

**Issue by InfiniteCanvas** [kobaltcore/renkit#5]
Input:
``./renutil install -v 7.4.11``
Output:
```
Downloading RAPT
httpclient.nim(886)      newConnection
Error: unhandled exception: SSL support is not available. Cannot connect over SSL. Compile with -d:ssl to enable. [HttpRequestError]
```

Debian Bullseye, x86_64
using v1.2.0

**Comment by kobaltcore** [comment]
Whoops, looks like I messed up the build flags when I refactored the build commands, apologies.
I'll make a new release with SSL support enabled in a couple minutes.

**Comment by InfiniteCanvas** [comment]
Thanks a lot. I'm glad I found your project, it makes a few things a lot easier.

**Comment by kobaltcore** [comment]
No problem. `v1.2.1` is now available, give it a whirl and let me know whether that one works.
It should, but always best to verify.

**Comment by InfiniteCanvas** [comment]
Installation works like a charm. I'll give building a try later.
Thank you for the quick fix!

**Comment by kobaltcore** [comment]
Nice, I'll close this issue then. If you run into any other problems, feel free to open a new issue where required.

**Comment by InfiniteCanvas** [comment]
Tried automated building. Everything works like it should, this makes CI/CD a loot easier. Great stuff!

**Comment by kobaltcore** [comment]
That's good to hear :)
I'm still working on adding more features to this (next up is getting notarization to work as part of the build process, after that is custom build tasks), so you can look forward to expanded capabilities soon-ish.
